/*



faAd&#13;faAddressBook, faAddressCard, faAdjust, faAirFreshener, faAlignCenter, faAlignJustify, faAlignLeft, faAlignRight, faAllergies, faAmbulance, faAmericanSignLanguageInterpreting, faAnchor, faAngleDoubleDown, faAngleDoubleLeft, faAngleDoubleRight, faAngleDoubleUp, faAngleDown, faAngleLeft, faAngleRight, faAngleUp, faAngry, faAnkh, faAppleAlt, faArchive, faArchway, faArrowAltCircleDown, faArrowAltCircleLeft, faArrowAltCircleRight, faArrowAltCircleUp, faArrowCircleDown, faArrowCircleLeft, faArrowCircleRight, faArrowCircleUp, faArrowDown, faArrowLeft, faArrowRight, faArrowUp, faArrowsAlt, faArrowsAltH, faArrowsAltV, faAssistiveListeningSystems, faAsterisk, faAt, faAtlas, faAtom, faAudioDescription, faAward, faBaby, faBabyCarriage, faBackspace, faBackward, faBacon, faBacteria, faBacterium, faBahai, faBalanceScale, faBalanceScaleLeft, faBalanceScaleRight, faBan, faBandAid, faBarcode, faBars, faBaseballBall, faBasketballBall, faBath, faBatteryEmpty, faBatteryFull, faBatteryHalf, faBatteryQuarter, faBatteryThreeQuarters, faBed, faBeer, faBell, faBellSlash, faBezierCurve, faBible, faBicycle, faBiking, faBinoculars, faBiohazard, faBirthdayCake, faBlender, faBlenderPhone, faBlind, faBlog, faBold, faBolt, faBomb, faBone, faBong, faBook, faBookDead, faBookMedical, faBookOpen, faBookReader, faBookmark, faBorderAll, faBorderNone, faBorderStyle, faBowlingBall, faBox, faBoxOpen, faBoxTissue, faBoxes, faBraille, faBrain, faBreadSlice, faBriefcase, faBriefcaseMedical, faBroadcastTower, faBroom, faBrush, faBug, faBuilding, faBullhorn, faBullseye, faBurn, faBus, faBusAlt, faBusinessTime, faCalculator, faCalendar, faCalendarAlt, faCalendarCheck, faCalendarDay, faCalendarMinus, faCalendarPlus, faCalendarTimes, faCalendarWeek, faCamera, faCameraRetro, faCampground, faCandyCane, faCannabis, faCapsules, faCar, faCarAlt, faCarBattery, faCarCrash, faCarSide, faCaravan, faCaretDown, faCaretLeft, faCaretRight, faCaretSquareDown, faCaretSquareLeft, faCaretSquareRight, faCaretSquareUp, faCaretUp, faCarrot, faCartArrowDown, faCartPlus, faCashRegister, faCat, faCertificate, faChair, faChalkboard, faChalkboardTeacher, faChargingStation, faChartArea, faChartBar, faChartLine, faChartPie, faCheck, faCheckCircle, faCheckDouble, faCheckSquare, faCheese, faChess, faChessBishop, faChessBoard, faChessKing, faChessKnight, faChessPawn, faChessQueen, faChessRook, faChevronCircleDown, faChevronCircleLeft, faChevronCircleRight, faChevronCircleUp, faChevronDown, faChevronLeft, faChevronRight, faChevronUp, faChild, faChurch, faCircle, faCircleNotch, faCity, faClinicMedical, faClipboard, faClipboardCheck, faClipboardList, faClock, faClone, faClosedCaptioning, faCloud, faCloudDownloadAlt, faCloudMeatball, faCloudMoon, faCloudMoonRain, faCloudRain, faCloudShowersHeavy, faCloudSun, faCloudSunRain, faCloudUploadAlt, faCocktail, faCode, faCodeBranch, faCoffee, faCog, faCogs, faCoins, faColumns, faComment, faCommentAlt, faCommentDollar, faCommentDots, faCommentMedical, faCommentSlash, faComments, faCommentsDollar, faCompactDisc, faCompass, faCompress, faCompressAlt, faCompressArrowsAlt, faConciergeBell, faCookie, faCookieBite, faCopy, faCopyright, faCouch, faCreditCard, faCrop, faCropAlt, faCross, faCrosshairs, faCrow, faCrown, faCrutch, faCube, faCubes, faCut, faDatabase, faDeaf, faDemocrat, faDesktop, faDharmachakra, faDiagnoses, faDice, faDiceD20, faDiceD6, faDiceFive, faDiceFour, faDiceOne, faDiceSix, faDiceThree, faDiceTwo, faDigitalTachograph, faDirections, faDisease, faDivide, faDizzy, faDna, faDog, faDollarSign, faDolly, faDollyFlatbed, faDonate, faDoorClosed, faDoorOpen, faDotCircle, faDove, faDownload, faDraftingCompass, faDragon, faDrawPolygon, faDrum, faDrumSteelpan, faDrumstickBite, faDumbbell, faDumpster, faDumpsterFire, faDungeon, faEdit, faEgg, faEject, faEllipsisH, faEllipsisV, faEnvelope, faEnvelopeOpen, faEnvelopeOpenText, faEnvelopeSquare, faEquals, faEraser, faEthernet, faEuroSign, faExchangeAlt, faExclamation, faExclamationCircle, faExclamationTriangle, faExpand, faExpandAlt, faExpandArrowsAlt, faExternalLinkAlt, faExternalLinkSquareAlt, faEye, faEyeDropper, faEyeSlash, faFan, faFastBackward, faFastForward, faFaucet, faFax, faFeather, faFeatherAlt, faFemale, faFighterJet, faFile, faFileAlt, faFileArchive, faFileAudio, faFileCode, faFileContract, faFileCsv, faFileDownload, faFileExcel, faFileExport, faFileImage, faFileImport, faFileInvoice, faFileInvoiceDollar, faFileMedical, faFileMedicalAlt, faFilePdf, faFilePowerpoint, faFilePrescription, faFileSignature, faFileUpload, faFileVideo, faFileWord, faFill, faFillDrip, faFilm, faFilter, faFingerprint, faFire, faFireAlt, faFireExtinguisher, faFirstAid, faFish, faFistRaised, faFlag, faFlagCheckered, faFlagUsa, faFlask, faFlushed, faFolder, faFolderMinus, faFolderOpen, faFolderPlus, faFont, faFontAwesomeLogoFull, faFootballBall, faForward, faFrog, faFrown, faFrownOpen, faFunnelDollar, faFutbol, faGamepad, faGasPump, faGavel, faGem, faGenderless, faGhost, faGift, faGifts, faGlassCheers, faGlassMartini, faGlassMartiniAlt, faGlassWhiskey, faGlasses, faGlobe, faGlobeAfrica, faGlobeAmericas, faGlobeAsia, faGlobeEurope, faGolfBall, faGopuram, faGraduationCap, faGreaterThan, faGreaterThanEqual, faGrimace, faGrin, faGrinAlt, faGrinBeam, faGrinBeamSweat, faGrinHearts, faGrinSquint, faGrinSquintTears, faGrinStars, faGrinTears, faGrinTongue, faGrinTongueSquint, faGrinTongueWink, faGrinWink, faGripHorizontal, faGripLines, faGripLinesVertical, faGripVertical, faGuitar, faHSquare, faHamburger, faHammer, faHamsa, faHandHolding, faHandHoldingHeart, faHandHoldingMedical, faHandHoldingUsd, faHandHoldingWater, faHandLizard, faHandMiddleFinger, faHandPaper, faHandPeace, faHandPointDown, faHandPointLeft, faHandPointRight, faHandPointUp, faHandPointer, faHandRock, faHandScissors, faHandSparkles, faHandSpock, faHands, faHandsHelping, faHandsWash, faHandshake, faHandshakeAltSlash, faHandshakeSlash, faHanukiah, faHardHat, faHashtag, faHatCowboy, faHatCowboySide, faHatWizard, faHdd, faHeadSideCough, faHeadSideCoughSlash, faHeadSideMask, faHeadSideVirus, faHeading, faHeadphones, faHeadphonesAlt, faHeadset, faHeart, faHeartBroken, faHeartbeat, faHelicopter, faHighlighter, faHiking, faHippo, faHistory, faHockeyPuck, faHollyBerry, faHome, faHorse, faHorseHead, faHospital, faHospitalAlt, faHospitalSymbol, faHospitalUser, faHotTub, faHotdog, faHotel, faHourglass, faHourglassEnd, faHourglassHalf, faHourglassStart, faHouseDamage, faHouseUser, faHryvnia, faICursor, faIceCream, faIcicles, faIcons, faIdBadge, faIdCard, faIdCardAlt, faIgloo, faImage, faImages, faInbox, faIndent, faIndustry, faInfinity, faInfo, faInfoCircle, faItalic, faJedi, faJoint, faJournalWhills, faKaaba, faKey, faKeyboard, faKhanda, faKiss, faKissBeam, faKissWinkHeart, faKiwiBird, faLandmark, faLanguage, faLaptop, faLaptopCode, faLaptopHouse, faLaptopMedical, faLaugh, faLaughBeam, faLaughSquint, faLaughWink, faLayerGroup, faLeaf, faLemon, faLessThan, faLessThanEqual, faLevelDownAlt, faLevelUpAlt, faLifeRing, faLightbulb, faLink, faLiraSign, faList, faListAlt, faListOl, faListUl, faLocationArrow, faLock, faLockOpen, faLongArrowAltDown, faLongArrowAltLeft, faLongArrowAltRight, faLongArrowAltUp, faLowVision, faLuggageCart, faLungs, faLungsVirus, faMagic, faMagnet, faMailBulk, faMale, faMap, faMapMarked, faMapMarkedAlt, faMapMarker, faMapMarkerAlt, faMapPin, faMapSigns, faMarker, faMars, faMarsDouble, faMarsStroke, faMarsStrokeH, faMarsStrokeV, faMask, faMedal, faMedkit, faMeh, faMehBlank, faMehRollingEyes, faMemory, faMenorah, faMercury, faMeteor, faMicrochip, faMicrophone, faMicrophoneAlt, faMicrophoneAltSlash, faMicrophoneSlash, faMicroscope, faMinus, faMinusCircle, faMinusSquare, faMitten, faMobile, faMobileAlt, faMoneyBill, faMoneyBillAlt, faMoneyBillWave, faMoneyBillWaveAlt, faMoneyCheck, faMoneyCheckAlt, faMonument, faMoon, faMortarPestle, faMosque, faMotorcycle, faMountain, faMouse, faMousePointer, faMugHot, faMusic, faNetworkWired, faNeuter, faNewspaper, faNotEqual, faNotesMedical, faObjectGroup, faObjectUngroup, faOilCan, faOm, faOtter, faOutdent, faPager, faPaintBrush, faPaintRoller, faPalette, faPallet, faPaperPlane, faPaperclip, faParachuteBox, faParagraph, faParking, faPassport, faPastafarianism, faPaste, faPause, faPauseCircle, faPaw, faPeace, faPen, faPenAlt, faPenFancy, faPenNib, faPenSquare, faPencilAlt, faPencilRuler, faPeopleArrows, faPeopleCarry, faPepperHot, faPercent, faPercentage, faPersonBooth, faPhone, faPhoneAlt, faPhoneSlash, faPhoneSquare, faPhoneSquareAlt, faPhoneVolume, faPhotoVideo, faPiggyBank, faPills, faPizzaSlice, faPlaceOfWorship, faPlane, faPlaneArrival, faPlaneDeparture, faPlaneSlash, faPlay, faPlayCircle, faPlug, faPlus, faPlusCircle, faPlusSquare, faPodcast, faPoll, faPollH, faPoo, faPooStorm, faPoop, faPortrait, faPoundSign, faPowerOff, faPray, faPrayingHands, faPrescription, faPrescriptionBottle, faPrescriptionBottleAlt, faPrint, faProcedures, faProjectDiagram, faPumpMedical, faPumpSoap, faPuzzlePiece, faQrcode, faQuestion, faQuestionCircle, faQuidditch, faQuoteLeft, faQuoteRight, faQuran, faRadiation, faRadiationAlt, faRainbow, faRandom, faReceipt, faRecordVinyl, faRecycle, faRedo, faRedoAlt, faRegistered, faRemoveFormat, faReply, faReplyAll, faRepublican, faRestroom, faRetweet, faRibbon, faRing, faRoad, faRobot, faRocket, faRoute, faRss, faRssSquare, faRubleSign, faRuler, faRulerCombined, faRulerHorizontal, faRulerVertical, faRunning, faRupeeSign, faSadCry, faSadTear, faSatellite, faSatelliteDish, faSave, faSchool, faScrewdriver, faScroll, faSdCard, faSearch, faSearchDollar, faSearchLocation, faSearchMinus, faSearchPlus, faSeedling, faServer, faShapes, faShare, faShareAlt, faShareAltSquare, faShareSquare, faShekelSign, faShieldAlt, faShieldVirus, faShip, faShippingFast, faShoePrints, faShoppingBag, faShoppingBasket, faShoppingCart, faShower, faShuttleVan, faSign, faSignInAlt, faSignLanguage, faSignOutAlt, faSignal, faSignature, faSimCard, faSink, faSitemap, faSkating, faSkiing, faSkiingNordic, faSkull, faSkullCrossbones, faSlash, faSleigh, faSlidersH, faSmile, faSmileBeam, faSmileWink, faSmog, faSmoking, faSmokingBan, faSms, faSnowboarding, faSnowflake, faSnowman, faSnowplow, faSoap, faSocks, faSolarPanel, faSort, faSortAlphaDown, faSortAlphaDownAlt, faSortAlphaUp, faSortAlphaUpAlt, faSortAmountDown, faSortAmountDownAlt, faSortAmountUp, faSortAmountUpAlt, faSortDown, faSortNumericDown, faSortNumericDownAlt, faSortNumericUp, faSortNumericUpAlt, faSortUp, faSpa, faSpaceShuttle, faSpellCheck, faSpider, faSpinner, faSplotch, faSprayCan, faSquare, faSquareFull, faSquareRootAlt, faStamp, faStar, faStarAndCrescent, faStarHalf, faStarHalfAlt, faStarOfDavid, faStarOfLife, faStepBackward, faStepForward, faStethoscope, faStickyNote, faStop, faStopCircle, faStopwatch, faStopwatch20, faStore, faStoreAlt, faStoreAltSlash, faStoreSlash, faStream, faStreetView, faStrikethrough, faStroopwafel, faSubscript, faSubway, faSuitcase, faSuitcaseRolling, faSun, faSuperscript, faSurprise, faSwatchbook, faSwimmer, faSwimmingPool, faSynagogue, faSync, faSyncAlt, faSyringe, faTable, faTableTennis, faTablet, faTabletAlt, faTablets, faTachometerAlt, faTag, faTags, faTape, faTasks, faTaxi, faTeeth, faTeethOpen, faTemperatureHigh, faTemperatureLow, faTenge, faTerminal, faTextHeight, faTextWidth, faTh, faThLarge, faThList, faTheaterMasks, faThermometer, faThermometerEmpty, faThermometerFull, faThermometerHalf, faThermometerQuarter, faThermometerThreeQuarters, faThumbsDown, faThumbsUp, faThumbtack, faTicketAlt, faTimes, faTimesCircle, faTint, faTintSlash, faTired, faToggleOff, faToggleOn, faToilet, faToiletPaper, faToiletPaperSlash, faToolbox, faTools, faTooth, faTorah, faToriiGate, faTractor, faTrademark, faTrafficLight, faTrailer, faTrain, faTram, faTransgender, faTransgenderAlt, faTrash, faTrashAlt, faTrashRestore, faTrashRestoreAlt, faTree, faTrophy, faTruck, faTruckLoading, faTruckMonster, faTruckMoving, faTruckPickup, faTshirt, faTty, faTv, faUmbrella, faUmbrellaBeach, faUnderline, faUndo, faUndoAlt, faUniversalAccess, faUniversity, faUnlink, faUnlock, faUnlockAlt, faUpload, faUser, faUserAlt, faUserAltSlash, faUserAstronaut, faUserCheck, faUserCircle, faUserClock, faUserCog, faUserEdit, faUserFriends, faUserGraduate, faUserInjured, faUserLock, faUserMd, faUserMinus, faUserNinja, faUserNurse, faUserPlus, faUserSecret, faUserShield, faUserSlash, faUserTag, faUserTie, faUserTimes, faUsers, faUsersCog, faUsersSlash, faUtensilSpoon, faUtensils, faVectorSquare, faVenus, faVenusDouble, faVenusMars, faVest, faVestPatches, faVial, faVials, faVideo, faVideoSlash, faVihara, faVirus, faVirusSlash, faViruses, faVoicemail, faVolleyballBall, faVolumeDown, faVolumeMute, faVolumeOff, faVolumeUp, faVoteYea, faVrCardboard, faWalking, faWallet, faWarehouse, faWater, faWaveSquare, faWeight, faWeightHanging, faWheelchair, faWifi, faWind, faWindowClose, faWindowMaximize, faWindowMinimize, faWindowRestore, faWineBottle, faWineGlass, faWineGlassAlt, faWonSign, faWrench, faXRay, faYenSign, faYinYang, fas, prefix








faAd
faAddressBook
faAddressCard
faAdjust
faAirFreshener
faAlignCenter
faAlignJustify
faAlignLeft
faAlignRight
faAllergies
faAmbulance
faAmericanSignLanguageInterpreting
faAnchor
faAngleDoubleDown
faAngleDoubleLeft
faAngleDoubleRight
faAngleDoubleUp
faAngleDown
faAngleLeft
faAngleRight
faAngleUp
faAngry
faAnkh
faAppleAlt
faArchive
faArchway
faArrowAltCircleDown
faArrowAltCircleLeft
faArrowAltCircleRight
faArrowAltCircleUp
faArrowCircleDown
faArrowCircleLeft
faArrowCircleRight
faArrowCircleUp
faArrowDown
faArrowLeft
faArrowRight
faArrowUp
faArrowsAlt
faArrowsAltH
faArrowsAltV
faAssistiveListeningSystems
faAsterisk
faAt
faAtlas
faAtom
faAudioDescription
faAward
faBaby
faBabyCarriage
faBackspace
faBackward
faBacon
faBacteria
faBacterium
faBahai
faBalanceScale
faBalanceScaleLeft
faBalanceScaleRight
faBan
faBandAid
faBarcode
faBars
faBaseballBall
faBasketballBall
faBath
faBatteryEmpty
faBatteryFull
faBatteryHalf
faBatteryQuarter
faBatteryThreeQuarters
faBed
faBeer
faBell
faBellSlash
faBezierCurve
faBible
faBicycle
faBiking
faBinoculars
faBiohazard
faBirthdayCake
faBlender
faBlenderPhone
faBlind
faBlog
faBold
faBolt
faBomb
faBone
faBong
faBook
faBookDead
faBookMedical
faBookOpen
faBookReader
faBookmark
faBorderAll
faBorderNone
faBorderStyle
faBowlingBall
faBox
faBoxOpen
faBoxTissue
faBoxes
faBraille
faBrain
faBreadSlice
faBriefcase
faBriefcaseMedical
faBroadcastTower
faBroom
faBrush
faBug
faBuilding
faBullhorn
faBullseye
faBurn
faBus
faBusAlt
faBusinessTime
faCalculator
faCalendar
faCalendarAlt
faCalendarCheck
faCalendarDay
faCalendarMinus
faCalendarPlus
faCalendarTimes
faCalendarWeek
faCamera
faCameraRetro
faCampground
faCandyCane
faCannabis
faCapsules
faCar
faCarAlt
faCarBattery
faCarCrash
faCarSide
faCaravan
faCaretDown
faCaretLeft
faCaretRight
faCaretSquareDown
faCaretSquareLeft
faCaretSquareRight
faCaretSquareUp
faCaretUp
faCarrot
faCartArrowDown
faCartPlus
faCashRegister
faCat
faCertificate
faChair
faChalkboard
faChalkboardTeacher
faChargingStation
faChartArea
faChartBar
faChartLine
faChartPie
faCheck
faCheckCircle
faCheckDouble
faCheckSquare
faCheese
faChess
faChessBishop
faChessBoard
faChessKing
faChessKnight
faChessPawn
faChessQueen
faChessRook
faChevronCircleDown
faChevronCircleLeft
faChevronCircleRight
faChevronCircleUp
faChevronDown
faChevronLeft
faChevronRight
faChevronUp
faChild
faChurch
faCircle
faCircleNotch
faCity
faClinicMedical
faClipboard
faClipboardCheck
faClipboardList
faClock
faClone
faClosedCaptioning
faCloud
faCloudDownloadAlt
faCloudMeatball
faCloudMoon
faCloudMoonRain
faCloudRain
faCloudShowersHeavy
faCloudSun
faCloudSunRain
faCloudUploadAlt
faCocktail
faCode
faCodeBranch
faCoffee
faCog
faCogs
faCoins
faColumns
faComment
faCommentAlt
faCommentDollar
faCommentDots
faCommentMedical
faCommentSlash
faComments
faCommentsDollar
faCompactDisc
faCompass
faCompress
faCompressAlt
faCompressArrowsAlt
faConciergeBell
faCookie
faCookieBite
faCopy
faCopyright
faCouch
faCreditCard
faCrop
faCropAlt
faCross
faCrosshairs
faCrow
faCrown
faCrutch
faCube
faCubes
faCut
faDatabase
faDeaf
faDemocrat
faDesktop
faDharmachakra
faDiagnoses
faDice
faDiceD20
faDiceD6
faDiceFive
faDiceFour
faDiceOne
faDiceSix
faDiceThree
faDiceTwo
faDigitalTachograph
faDirections
faDisease
faDivide
faDizzy
faDna
faDog
faDollarSign
faDolly
faDollyFlatbed
faDonate
faDoorClosed
faDoorOpen
faDotCircle
faDove
faDownload
faDraftingCompass
faDragon
faDrawPolygon
faDrum
faDrumSteelpan
faDrumstickBite
faDumbbell
faDumpster
faDumpsterFire
faDungeon
faEdit
faEgg
faEject
faEllipsisH
faEllipsisV
faEnvelope
faEnvelopeOpen
faEnvelopeOpenText
faEnvelopeSquare
faEquals
faEraser
faEthernet
faEuroSign
faExchangeAlt
faExclamation
faExclamationCircle
faExclamationTriangle
faExpand
faExpandAlt
faExpandArrowsAlt
faExternalLinkAlt
faExternalLinkSquareAlt
faEye
faEyeDropper
faEyeSlash
faFan
faFastBackward
faFastForward
faFaucet
faFax
faFeather
faFeatherAlt
faFemale
faFighterJet
faFile
faFileAlt
faFileArchive
faFileAudio
faFileCode
faFileContract
faFileCsv
faFileDownload
faFileExcel
faFileExport
faFileImage
faFileImport
faFileInvoice
faFileInvoiceDollar
faFileMedical
faFileMedicalAlt
faFilePdf
faFilePowerpoint
faFilePrescription
faFileSignature
faFileUpload
faFileVideo
faFileWord
faFill
faFillDrip
faFilm
faFilter
faFingerprint
faFire
faFireAlt
faFireExtinguisher
faFirstAid
faFish
faFistRaised
faFlag
faFlagCheckered
faFlagUsa
faFlask
faFlushed
faFolder
faFolderMinus
faFolderOpen
faFolderPlus
faFont
faFontAwesomeLogoFull
faFootballBall
faForward
faFrog
faFrown
faFrownOpen
faFunnelDollar
faFutbol
faGamepad
faGasPump
faGavel
faGem
faGenderless
faGhost
faGift
faGifts
faGlassCheers
faGlassMartini
faGlassMartiniAlt
faGlassWhiskey
faGlasses
faGlobe
faGlobeAfrica
faGlobeAmericas
faGlobeAsia
faGlobeEurope
faGolfBall
faGopuram
faGraduationCap
faGreaterThan
faGreaterThanEqual
faGrimace
faGrin
faGrinAlt
faGrinBeam
faGrinBeamSweat
faGrinHearts
faGrinSquint
faGrinSquintTears
faGrinStars
faGrinTears
faGrinTongue
faGrinTongueSquint
faGrinTongueWink
faGrinWink
faGripHorizontal
faGripLines
faGripLinesVertical
faGripVertical
faGuitar
faHSquare
faHamburger
faHammer
faHamsa
faHandHolding
faHandHoldingHeart
faHandHoldingMedical
faHandHoldingUsd
faHandHoldingWater
faHandLizard
faHandMiddleFinger
faHandPaper
faHandPeace
faHandPointDown
faHandPointLeft
faHandPointRight
faHandPointUp
faHandPointer
faHandRock
faHandScissors
faHandSparkles
faHandSpock
faHands
faHandsHelping
faHandsWash
faHandshake
faHandshakeAltSlash
faHandshakeSlash
faHanukiah
faHardHat
faHashtag
faHatCowboy
faHatCowboySide
faHatWizard
faHdd
faHeadSideCough
faHeadSideCoughSlash
faHeadSideMask
faHeadSideVirus
faHeading
faHeadphones
faHeadphonesAlt
faHeadset
faHeart
faHeartBroken
faHeartbeat
faHelicopter
faHighlighter
faHiking
faHippo
faHistory
faHockeyPuck
faHollyBerry
faHome
faHorse
faHorseHead
faHospital
faHospitalAlt
faHospitalSymbol
faHospitalUser
faHotTub
faHotdog
faHotel
faHourglass
faHourglassEnd
faHourglassHalf
faHourglassStart
faHouseDamage
faHouseUser
faHryvnia
faICursor
faIceCream
faIcicles
faIcons
faIdBadge
faIdCard
faIdCardAlt
faIgloo
faImage
faImages
faInbox
faIndent
faIndustry
faInfinity
faInfo
faInfoCircle
faItalic
faJedi
faJoint
faJournalWhills
faKaaba
faKey
faKeyboard
faKhanda
faKiss
faKissBeam
faKissWinkHeart
faKiwiBird
faLandmark
faLanguage
faLaptop
faLaptopCode
faLaptopHouse
faLaptopMedical
faLaugh
faLaughBeam
faLaughSquint
faLaughWink
faLayerGroup
faLeaf
faLemon
faLessThan
faLessThanEqual
faLevelDownAlt
faLevelUpAlt
faLifeRing
faLightbulb
faLink
faLiraSign
faList
faListAlt
faListOl
faListUl
faLocationArrow
faLock
faLockOpen
faLongArrowAltDown
faLongArrowAltLeft
faLongArrowAltRight
faLongArrowAltUp
faLowVision
faLuggageCart
faLungs
faLungsVirus
faMagic
faMagnet
faMailBulk
faMale
faMap
faMapMarked
faMapMarkedAlt
faMapMarker
faMapMarkerAlt
faMapPin
faMapSigns
faMarker
faMars
faMarsDouble
faMarsStroke
faMarsStrokeH
faMarsStrokeV
faMask
faMedal
faMedkit
faMeh
faMehBlank
faMehRollingEyes
faMemory
faMenorah
faMercury
faMeteor
faMicrochip
faMicrophone
faMicrophoneAlt
faMicrophoneAltSlash
faMicrophoneSlash
faMicroscope
faMinus
faMinusCircle
faMinusSquare
faMitten
faMobile
faMobileAlt
faMoneyBill
faMoneyBillAlt
faMoneyBillWave
faMoneyBillWaveAlt
faMoneyCheck
faMoneyCheckAlt
faMonument
faMoon
faMortarPestle
faMosque
faMotorcycle
faMountain
faMouse
faMousePointer
faMugHot
faMusic
faNetworkWired
faNeuter
faNewspaper
faNotEqual
faNotesMedical
faObjectGroup
faObjectUngroup
faOilCan
faOm
faOtter
faOutdent
faPager
faPaintBrush
faPaintRoller
faPalette
faPallet
faPaperPlane
faPaperclip
faParachuteBox
faParagraph
faParking
faPassport
faPastafarianism
faPaste
faPause
faPauseCircle
faPaw
faPeace
faPen
faPenAlt
faPenFancy
faPenNib
faPenSquare
faPencilAlt
faPencilRuler
faPeopleArrows
faPeopleCarry
faPepperHot
faPercent
faPercentage
faPersonBooth
faPhone
faPhoneAlt
faPhoneSlash
faPhoneSquare
faPhoneSquareAlt
faPhoneVolume
faPhotoVideo
faPiggyBank
faPills
faPizzaSlice
faPlaceOfWorship
faPlane
faPlaneArrival
faPlaneDeparture
faPlaneSlash
faPlay
faPlayCircle
faPlug
faPlus
faPlusCircle
faPlusSquare
faPodcast
faPoll
faPollH
faPoo
faPooStorm
faPoop
faPortrait
faPoundSign
faPowerOff
faPray
faPrayingHands
faPrescription
faPrescriptionBottle
faPrescriptionBottleAlt
faPrint
faProcedures
faProjectDiagram
faPumpMedical
faPumpSoap
faPuzzlePiece
faQrcode
faQuestion
faQuestionCircle
faQuidditch
faQuoteLeft
faQuoteRight
faQuran
faRadiation
faRadiationAlt
faRainbow
faRandom
faReceipt
faRecordVinyl
faRecycle
faRedo
faRedoAlt
faRegistered
faRemoveFormat
faReply
faReplyAll
faRepublican
faRestroom
faRetweet
faRibbon
faRing
faRoad
faRobot
faRocket
faRoute
faRss
faRssSquare
faRubleSign
faRuler
faRulerCombined
faRulerHorizontal
faRulerVertical
faRunning
faRupeeSign
faSadCry
faSadTear
faSatellite
faSatelliteDish
faSave
faSchool
faScrewdriver
faScroll
faSdCard
faSearch
faSearchDollar
faSearchLocation
faSearchMinus
faSearchPlus
faSeedling
faServer
faShapes
faShare
faShareAlt
faShareAltSquare
faShareSquare
faShekelSign
faShieldAlt
faShieldVirus
faShip
faShippingFast
faShoePrints
faShoppingBag
faShoppingBasket
faShoppingCart
faShower
faShuttleVan
faSign
faSignInAlt
faSignLanguage
faSignOutAlt
faSignal
faSignature
faSimCard
faSink
faSitemap
faSkating
faSkiing
faSkiingNordic
faSkull
faSkullCrossbones
faSlash
faSleigh
faSlidersH
faSmile
faSmileBeam
faSmileWink
faSmog
faSmoking
faSmokingBan
faSms
faSnowboarding
faSnowflake
faSnowman
faSnowplow
faSoap
faSocks
faSolarPanel
faSort
faSortAlphaDown
faSortAlphaDownAlt
faSortAlphaUp
faSortAlphaUpAlt
faSortAmountDown
faSortAmountDownAlt
faSortAmountUp
faSortAmountUpAlt
faSortDown
faSortNumericDown
faSortNumericDownAlt
faSortNumericUp
faSortNumericUpAlt
faSortUp
faSpa
faSpaceShuttle
faSpellCheck
faSpider
faSpinner
faSplotch
faSprayCan
faSquare
faSquareFull
faSquareRootAlt
faStamp
faStar
faStarAndCrescent
faStarHalf
faStarHalfAlt
faStarOfDavid
faStarOfLife
faStepBackward
faStepForward
faStethoscope
faStickyNote
faStop
faStopCircle
faStopwatch
faStopwatch20
faStore
faStoreAlt
faStoreAltSlash
faStoreSlash
faStream
faStreetView
faStrikethrough
faStroopwafel
faSubscript
faSubway
faSuitcase
faSuitcaseRolling
faSun
faSuperscript
faSurprise
faSwatchbook
faSwimmer
faSwimmingPool
faSynagogue
faSync
faSyncAlt
faSyringe
faTable
faTableTennis
faTablet
faTabletAlt
faTablets
faTachometerAlt
faTag
faTags
faTape
faTasks
faTaxi
faTeeth
faTeethOpen
faTemperatureHigh
faTemperatureLow
faTenge
faTerminal
faTextHeight
faTextWidth
faTh
faThLarge
faThList
faTheaterMasks
faThermometer
faThermometerEmpty
faThermometerFull
faThermometerHalf
faThermometerQuarter
faThermometerThreeQuarters
faThumbsDown
faThumbsUp
faThumbtack
faTicketAlt
faTimes
faTimesCircle
faTint
faTintSlash
faTired
faToggleOff
faToggleOn
faToilet
faToiletPaper
faToiletPaperSlash
faToolbox
faTools
faTooth
faTorah
faToriiGate
faTractor
faTrademark
faTrafficLight
faTrailer
faTrain
faTram
faTransgender
faTransgenderAlt
faTrash
faTrashAlt
faTrashRestore
faTrashRestoreAlt
faTree
faTrophy
faTruck
faTruckLoading
faTruckMonster
faTruckMoving
faTruckPickup
faTshirt
faTty
faTv
faUmbrella
faUmbrellaBeach
faUnderline
faUndo
faUndoAlt
faUniversalAccess
faUniversity
faUnlink
faUnlock
faUnlockAlt
faUpload
faUser
faUserAlt
faUserAltSlash
faUserAstronaut
faUserCheck
faUserCircle
faUserClock
faUserCog
faUserEdit
faUserFriends
faUserGraduate
faUserInjured
faUserLock
faUserMd
faUserMinus
faUserNinja
faUserNurse
faUserPlus
faUserSecret
faUserShield
faUserSlash
faUserTag
faUserTie
faUserTimes
faUsers
faUsersCog
faUsersSlash
faUtensilSpoon
faUtensils
faVectorSquare
faVenus
faVenusDouble
faVenusMars
faVest
faVestPatches
faVial
faVials
faVideo
faVideoSlash
faVihara
faVirus
faVirusSlash
faViruses
faVoicemail
faVolleyballBall
faVolumeDown
faVolumeMute
faVolumeOff
faVolumeUp
faVoteYea
faVrCardboard
faWalking
faWallet
faWarehouse
faWater
faWaveSquare
faWeight
faWeightHanging
faWheelchair
faWifi
faWind
faWindowClose
faWindowMaximize
faWindowMinimize
faWindowRestore
faWineBottle
faWineGlass
faWineGlassAlt
faWonSign
faWrench
faXRay
faYenSign
faYinYang

ad
address-book
address-card
adjust
air-freshener
align-center
align-justify
align-left
align-right
allergies
ambulance
american-sign-language-interpreting
anchor
angle-double-down
angle-double-left
angle-double-right
angle-double-up
angle-down
angle-left
angle-right
angle-up
angry
ankh
apple-alt
archive
archway
arrow-alt-circle-down
arrow-alt-circle-left
arrow-alt-circle-right
arrow-alt-circle-up
arrow-circle-down
arrow-circle-left
arrow-circle-right
arrow-circle-up
arrow-down
arrow-left
arrow-right
arrow-up
arrows-alt
arrows-alt-h
arrows-alt-v
assistive-listening-systems
asterisk
at
atlas
atom
audio-description
award
baby
baby-carriage
backspace
backward
bacon
bacteria
bacterium
bahai
balance-scale
balance-scale-left
balance-scale-right
ban
band-aid
barcode
bars
baseball-ball
basketball-ball
bath
battery-empty
battery-full
battery-half
battery-quarter
battery-three-quarters
bed
beer
bell
bell-slash
bezier-curve
bible
bicycle
biking
binoculars
biohazard
birthday-cake
blender
blender-phone
blind
blog
bold
bolt
bomb
bone
bong
book
book-dead
book-medical
book-open
book-reader
bookmark
border-all
border-none
border-style
bowling-ball
box
box-open
box-tissue
boxes
braille
brain
bread-slice
briefcase
briefcase-medical
broadcast-tower
broom
brush
bug
building
bullhorn
bullseye
burn
bus
bus-alt
business-time
calculator
calendar
calendar-alt
calendar-check
calendar-day
calendar-minus
calendar-plus
calendar-times
calendar-week
camera
camera-retro
campground
candy-cane
cannabis
capsules
car
car-alt
car-battery
car-crash
car-side
caravan
caret-down
caret-left
caret-right
caret-square-down
caret-square-left
caret-square-right
caret-square-up
caret-up
carrot
cart-arrow-down
cart-plus
cash-register
cat
certificate
chair
chalkboard
chalkboard-teacher
charging-station
chart-area
chart-bar
chart-line
chart-pie
check
check-circle
check-double
check-square
cheese
chess
chess-bishop
chess-board
chess-king
chess-knight
chess-pawn
chess-queen
chess-rook
chevron-circle-down
chevron-circle-left
chevron-circle-right
chevron-circle-up
chevron-down
chevron-left
chevron-right
chevron-up
child
church
circle
circle-notch
city
clinic-medical
clipboard
clipboard-check
clipboard-list
clock
clone
closed-captioning
cloud
cloud-download-alt
cloud-meatball
cloud-moon
cloud-moon-rain
cloud-rain
cloud-showers-heavy
cloud-sun
cloud-sun-rain
cloud-upload-alt
cocktail
code
code-branch
coffee
cog
cogs
coins
columns
comment
comment-alt
comment-dollar
comment-dots
comment-medical
comment-slash
comments
comments-dollar
compact-disc
compass
compress
compress-alt
compress-arrows-alt
concierge-bell
cookie
cookie-bite
copy
copyright
couch
credit-card
crop
crop-alt
cross
crosshairs
crow
crown
crutch
cube
cubes
cut
database
deaf
democrat
desktop
dharmachakra
diagnoses
dice
dice-d20
dice-d6
dice-five
dice-four
dice-one
dice-six
dice-three
dice-two
digital-tachograph
directions
disease
divide
dizzy
dna
dog
dollar-sign
dolly
dolly-flatbed
donate
door-closed
door-open
dot-circle
dove
download
drafting-compass
dragon
draw-polygon
drum
drum-steelpan
drumstick-bite
dumbbell
dumpster
dumpster-fire
dungeon
edit
egg
eject
ellipsis-h
ellipsis-v
envelope
envelope-open
envelope-open-text
envelope-square
equals
eraser
ethernet
euro-sign
exchange-alt
exclamation
exclamation-circle
exclamation-triangle
expand
expand-alt
expand-arrows-alt
external-link-alt
external-link-square-alt
eye
eye-dropper
eye-slash
fan
fast-backward
fast-forward
faucet
fax
feather
feather-alt
female
fighter-jet
file
file-alt
file-archive
file-audio
file-code
file-contract
file-csv
file-download
file-excel
file-export
file-image
file-import
file-invoice
file-invoice-dollar
file-medical
file-medical-alt
file-pdf
file-powerpoint
file-prescription
file-signature
file-upload
file-video
file-word
fill
fill-drip
film
filter
fingerprint
fire
fire-alt
fire-extinguisher
first-aid
fish
fist-raised
flag
flag-checkered
flag-usa
flask
flushed
folder
folder-minus
folder-open
folder-plus
font
font-awesome-logo-full
football-ball
forward
frog
frown
frown-open
funnel-dollar
futbol
gamepad
gas-pump
gavel
gem
genderless
ghost
gift
gifts
glass-cheers
glass-martini
glass-martini-alt
glass-whiskey
glasses
globe
globe-africa
globe-americas
globe-asia
globe-europe
golf-ball
gopuram
graduation-cap
greater-than
greater-than-equal
grimace
grin
grin-alt
grin-beam
grin-beam-sweat
grin-hearts
grin-squint
grin-squint-tears
grin-stars
grin-tears
grin-tongue
grin-tongue-squint
grin-tongue-wink
grin-wink
grip-horizontal
grip-lines
grip-lines-vertical
grip-vertical
guitar
h-square
hamburger
hammer
hamsa
hand-holding
hand-holding-heart
hand-holding-medical
hand-holding-usd
hand-holding-water
hand-lizard
hand-middle-finger
hand-paper
hand-peace
hand-point-down
hand-point-left
hand-point-right
hand-point-up
hand-pointer
hand-rock
hand-scissors
hand-sparkles
hand-spock
hands
hands-helping
hands-wash
handshake
handshake-alt-slash
handshake-slash
hanukiah
hard-hat
hashtag
hat-cowboy
hat-cowboy-side
hat-wizard
hdd
head-side-cough
head-side-cough-slash
head-side-mask
head-side-virus
heading
headphones
headphones-alt
headset
heart
heart-broken
heartbeat
helicopter
highlighter
hiking
hippo
history
hockey-puck
holly-berry
home
horse
horse-head
hospital
hospital-alt
hospital-symbol
hospital-user
hot-tub
hotdog
hotel
hourglass
hourglass-end
hourglass-half
hourglass-start
house-damage
house-user
hryvnia
i-cursor
ice-cream
icicles
icons
id-badge
id-card
id-card-alt
igloo
image
images
inbox
indent
industry
infinity
info
info-circle
italic
jedi
joint
journal-whills
kaaba
key
keyboard
khanda
kiss
kiss-beam
kiss-wink-heart
kiwi-bird
landmark
language
laptop
laptop-code
laptop-house
laptop-medical
laugh
laugh-beam
laugh-squint
laugh-wink
layer-group
leaf
lemon
less-than
less-than-equal
level-down-alt
level-up-alt
life-ring
lightbulb
link
lira-sign
list
list-alt
list-ol
list-ul
location-arrow
lock
lock-open
long-arrow-alt-down
long-arrow-alt-left
long-arrow-alt-right
long-arrow-alt-up
low-vision
luggage-cart
lungs
lungs-virus
magic
magnet
mail-bulk
male
map
map-marked
map-marked-alt
map-marker
map-marker-alt
map-pin
map-signs
marker
mars
mars-double
mars-stroke
mars-stroke-h
mars-stroke-v
mask
medal
medkit
meh
meh-blank
meh-rolling-eyes
memory
menorah
mercury
meteor
microchip
microphone
microphone-alt
microphone-alt-slash
microphone-slash
microscope
minus
minus-circle
minus-square
mitten
mobile
mobile-alt
money-bill
money-bill-alt
money-bill-wave
money-bill-wave-alt
money-check
money-check-alt
monument
moon
mortar-pestle
mosque
motorcycle
mountain
mouse
mouse-pointer
mug-hot
music
network-wired
neuter
newspaper
not-equal
notes-medical
object-group
object-ungroup
oil-can
om
otter
outdent
pager
paint-brush
paint-roller
palette
pallet
paper-plane
paperclip
parachute-box
paragraph
parking
passport
pastafarianism
paste
pause
pause-circle
paw
peace
pen
pen-alt
pen-fancy
pen-nib
pen-square
pencil-alt
pencil-ruler
people-arrows
people-carry
pepper-hot
percent
percentage
person-booth
phone
phone-alt
phone-slash
phone-square
phone-square-alt
phone-volume
photo-video
piggy-bank
pills
pizza-slice
place-of-worship
plane
plane-arrival
plane-departure
plane-slash
play
play-circle
plug
plus
plus-circle
plus-square
podcast
poll
poll-h
poo
poo-storm
poop
portrait
pound-sign
power-off
pray
praying-hands
prescription
prescription-bottle
prescription-bottle-alt
print
procedures
project-diagram
pump-medical
pump-soap
puzzle-piece
qrcode
question
question-circle
quidditch
quote-left
quote-right
quran
radiation
radiation-alt
rainbow
random
receipt
record-vinyl
recycle
redo
redo-alt
registered
remove-format
reply
reply-all
republican
restroom
retweet
ribbon
ring
road
robot
rocket
route
rss
rss-square
ruble-sign
ruler
ruler-combined
ruler-horizontal
ruler-vertical
running
rupee-sign
sad-cry
sad-tear
satellite
satellite-dish
save
school
screwdriver
scroll
sd-card
search
search-dollar
search-location
search-minus
search-plus
seedling
server
shapes
share
share-alt
share-alt-square
share-square
shekel-sign
shield-alt
shield-virus
ship
shipping-fast
shoe-prints
shopping-bag
shopping-basket
shopping-cart
shower
shuttle-van
sign
sign-in-alt
sign-language
sign-out-alt
signal
signature
sim-card
sink
sitemap
skating
skiing
skiing-nordic
skull
skull-crossbones
slash
sleigh
sliders-h
smile
smile-beam
smile-wink
smog
smoking
smoking-ban
sms
snowboarding
snowflake
snowman
snowplow
soap
socks
solar-panel
sort
sort-alpha-down
sort-alpha-down-alt
sort-alpha-up
sort-alpha-up-alt
sort-amount-down
sort-amount-down-alt
sort-amount-up
sort-amount-up-alt
sort-down
sort-numeric-down
sort-numeric-down-alt
sort-numeric-up
sort-numeric-up-alt
sort-up
spa
space-shuttle
spell-check
spider
spinner
splotch
spray-can
square
square-full
square-root-alt
stamp
star
star-and-crescent
star-half
star-half-alt
star-of-david
star-of-life
step-backward
step-forward
stethoscope
sticky-note
stop
stop-circle
stopwatch
stopwatch-20
store
store-alt
store-alt-slash
store-slash
stream
street-view
strikethrough
stroopwafel
subscript
subway
suitcase
suitcase-rolling
sun
superscript
surprise
swatchbook
swimmer
swimming-pool
synagogue
sync
sync-alt
syringe
table
table-tennis
tablet
tablet-alt
tablets
tachometer-alt
tag
tags
tape
tasks
taxi
teeth
teeth-open
temperature-high
temperature-low
tenge
terminal
text-height
text-width
th
th-large
th-list
theater-masks
thermometer
thermometer-empty
thermometer-full
thermometer-half
thermometer-quarter
thermometer-three-quarters
thumbs-down
thumbs-up
thumbtack
ticket-alt
times
times-circle
tint
tint-slash
tired
toggle-off
toggle-on
toilet
toilet-paper
toilet-paper-slash
toolbox
tools
tooth
torah
torii-gate
tractor
trademark
traffic-light
trailer
train
tram
transgender
transgender-alt
trash
trash-alt
trash-restore
trash-restore-alt
tree
trophy
truck
truck-loading
truck-monster
truck-moving
truck-pickup
tshirt
tty
tv
umbrella
umbrella-beach
underline
undo
undo-alt
universal-access
university
unlink
unlock
unlock-alt
upload
user
user-alt
user-alt-slash
user-astronaut
user-check
user-circle
user-clock
user-cog
user-edit
user-friends
user-graduate
user-injured
user-lock
user-md
user-minus
user-ninja
user-nurse
user-plus
user-secret
user-shield
user-slash
user-tag
user-tie
user-times
users
users-cog
users-slash
utensil-spoon
utensils
vector-square
venus
venus-double
venus-mars
vest
vest-patches
vial
vials
video
video-slash
vihara
virus
virus-slash
viruses
voicemail
volleyball-ball
volume-down
volume-mute
volume-off
volume-up
vote-yea
vr-cardboard
walking
wallet
warehouse
water
wave-square
weight
weight-hanging
wheelchair
wifi
wind
window-close
window-maximize
window-minimize
window-restore
wine-bottle
wine-glass
wine-glass-alt
won-sign
wrench
x-ray
yen-sign
yin-yang




*/